### ISSUE TITLE
[1.20.1 Fabric] Server Crashes when fish bites

### ISSUE THREAD

**Issue by SillviaTV** [Lightning-64/Tide#7]
The crash is related to the bobber ticking and a parameter called minecraft:last_damage_player

```
Description: Ticking entity

java.lang.IllegalArgumentException: Parameters not allowed in this parameter set: [<parameter minecraft:last_damage_player>]
	at net.minecraft.class_8567$class_8568.method_51875(class_8567.java:136)
	at com.li64.tide.registries.entities.misc.fishing.TideFishingHook.selectCatch(TideFishingHook.java:662)
	at com.li64.tide.registries.entities.misc.fishing.TideFishingHook.catchingFish(TideFishingHook.java:439)
	at com.li64.tide.registries.entities.misc.fishing.TideFishingHook.method_5773(TideFishingHook.java:295)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

I have other mods installed but just wanted to raise it here as it's related to the mod entity

**Comment by Lightning-64** [comment]
Fixed! I put out a new version that solves this problem (posted as Tide 1.3.2-1.20.1 (FABRIC) (fix) on curseforge and modrinth)
